### ISSUE TITLE
GATE NET BUTTON

### ISSUE THREAD

**Issue by matsiyan** [tsnrp/navcon#1]
Can the GATE NET button please
- show "VIEW UPPER ARC" when viewing
 > sectors of an UPPER ARC system
 > the LOWER ARC gate net

- show "VIEW LOWER ARC" when viewing
 > sectors of a LOWER ARC system
 > the UPPER ARC gate net

**Comment by StarryWisdom** [comment]
commit 111db9bf9d982691d292fd1e390df1b98293c0aa
