### ISSUE TITLE
Classified flag not working consistently

### ISSUE THREAD

**Issue by matsiyan** [tsnrp/navcon#15]
In the new Loria system entities.txt file, three lines are flagged as Classified
Taylor Denabite,I,8,Classified
Joshua Tree Denabite,F,10,Classified
Tiffan Denabite,F,15,Classified

But only Tiffan is hidden in the public view. The other two appear in both Classified and Public view.

**Comment by StarryWisdom** [comment]
I was unable to directly reproduce on a local machine
I managed to induce a similar bug via swaping newlines from unix style to dos style
I have no idea how dos style new lines would of got onto whatever machine you are using for testing (ftp client settings? the autoupdater?)
can you see if the latest commit fixed this on the machine you saw it on

**Comment by matsiyan** [comment]
If not everyone was editing with something like Notepad++ with the linux newlines setting.
I will upload and test.

**Comment by matsiyan** [comment]
Confirmed fixed
