### ISSUE TITLE
Restrict Systems Menu List

### ISSUE THREAD

**Issue by matsiyan** [tsnrp/navcon#2]
Can the SYSTEMS menu list content be restricted to 
- 1 the GATE NET ARC currently visible
or
- 2 the GATE NET ARC of the sectors currently on view

**Comment by matsiyan** [comment]
This will be a design decision whether to show systems relating to current arc or to keep a single large list and increase the list paging. Currently planning to try the latter.

**Comment by StarryWisdom** [comment]
if we change out mind - 
inside the main loop in getSystemsMenus
if (getGateNetworkFromSector($classified,$name)=="GATE ARC") {
could be added to filter
it looks like this isnt wanted anymore, but I wanted to leave this comment somewhere in case that changes
