### ISSUE TITLE
gate net image doesn't scroll properly in browser windows

### ISSUE THREAD

**Issue by StarryWisdom** [tsnrp/navcon#4]
the original one from about a year back did - when the clickables where added the formatting changed and it broke

**Comment by matsiyan** [comment]
I don't think it ever scrolled. Before we added the clickables, it used to scale to the window.
It would be nice if scrollbars were allowed. But if that was true, we would not actually need to split the map...

**Comment by StarryWisdom** [comment]
it was broken in a different way (I think) before the clickables update - maybe with figuring out what changed and why some sort of insperation will hit, at the very least assuming it was broken in a different way having the old code saved somewhere would be good (I have a local git repo to pull it out of)

**Comment by StarryWisdom** [comment]
Thinking about it - I seem to recall how it was broken before was that the image didnt have scroll bars but did shrink to fit the screen
I would like to look at the old html and figure out what I changed, but it seems to be the before the first version I have in my pre github git archive
Do we happen to have old (about a year+) copies of the code anywhere?

**Comment by StarryWisdom** [comment]
I think this now works.
it needs testing in as many browsers as I can get my hands on.
I seem to recall it worked in some and didnt in others last time I tried to fix it.

**Comment by astrolamb-gaming** [comment]
Closing issue as the issue was supsected to be resolved in July 2019 and no further problems have been reported.
