### ISSUE TITLE
Euphini Expanse post invertVertical removal

### ISSUE THREAD

**Issue by StarryWisdom** [tsnrp/navcon#6]
I think that the numbering of the images after the removal of invertVertical is off

I can fix this myself but would like confirmation that the map on http://www.1sws.com/Intel/Nav/?sector=Euphini%20Expanse is correct and current (rather than this change being intended as part of a sandbox update say)

also the entities.txt numbering is now off (resulting in the sub sector map being incorrect)

**Comment by matsiyan** [comment]
Corrected image file numbering and entities.txt location file
